export const EmailPlans = [
  {
    id: "pro",
    name: "Pro",
    priceMonthly: "P35",
    priceYearly: "350",
    description: "ideal for personal use and small businesses",
    features: [
      "1 Email Account",
      "Multiple Accounts: NO",
      "Email Alias: 1",
      "5GB Storage",
      "200 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-pro`,
    linkText: "Get Basic",
    featured: false,
  },
  {
    id: "business",
    name: "Business",
    priceMonthly: "P60",
    priceYearly: "P600",
    description: "Ideal for businesses and organisations.",
    features: [
      "1 or more Accounts",
      "Multiple Accounts: YES",
      "Email Alias: 10",
      "10GB Storage/acc",
      "300 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-business`,
    linkText: "Get Business",
    featured: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: "P120",
    priceYearly: "P1200",
    description: "Perfect for large businesses and enterprises.",
    features: [
      "1 or more Accounts",
      "Multiple Accounts: YES",
      "Email Alias: 10",
      "50GB Storage/acc",
      "500 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-enterprise`,
    linkText: "Get Enterprise",
    featured: false,
  },
];
