export const EmailPlans = [
  {
    id: "basic",
    name: "DeltaMail Starter",
    priceMonthly: "P50",
    priceYearly: "500",
    description: "ideal for personal use and small businesses",
    features: [
      "1 Admin Account",
      "5 Email Accounts",
      "10GB Storage",
      "Business Suite",
      "600 Emails/hour per Domain",
      "Premium Email Deliverability",
      "POP3/IMAP/SMTP",
    ],
    href: "https://domains.bigzee.app/index.php?rp=/store/business-email/basic-email",
    linkText: "Get Basic",
    featured: false,
  },
  {
    id: "pro",
    name: "DeltaMail Pro",
    priceMonthly: "P85",
    priceYearly: "P850",
    description: "Ideal for businesses and organisations.",
    features: [
      "1 Admin Account",
      "10 Email Accounts",
      "50GB Storage",
      "Business Suite",
      "600 Emails/hour per Domain",
      "Premium Email Deliverability",
      "POP3/IMAP/SMTP",
    ],
    href: "https://domains.bigzee.app/index.php?rp=/store/business-email/business-email",
    linkText: "Get Business",
    featured: true,
  },
  {
    id: "enterprise",
    name: "DeltaMail Enterprise",
    priceMonthly: "P140",
    priceYearly: "P1400",
    description: "Perfect for large businesses and enterprises.",
    features: [
      "1 Admin Account",
      "20 Email Accounts",
      "100GB Storage",
      "Business Suite",
      "600 Emails/hour per Domain",
      "Premium Email Deliverability",
      "POP3/IMAP/SMTP",
    ],
    href: "https://domains.bigzee.app/index.php?rp=/store/business-email/enterprise-email",
    linkText: "Get Enterprise",
    featured: false,
  },
];
