export const EmailPlans = [
  {
    id: "pro",
    name: "Pro",
    priceMonthly: { BWP: "35", USD: "2.50" },
    priceYearly: { BWP: "350", USD: "25.00" },
    description: "ideal for personal use and small businesses",
    features: [
      "1 Email Account",
      "Multiple Accounts: NO",
      "Email Alias: 1",
      "5GB Storage",
      "200 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-pro&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-pro&billingcycle=annually`,
    linkText: "Get Basic",
    featured: false,
  },
  {
    id: "business",
    name: "Business",
    priceMonthly: { BWP: "60", USD: "4.00" },
    priceYearly: { BWP: "600", USD: "40.00" },
    description: "Ideal for businesses and organisations.",
    features: [
      "1 or more Accounts",
      "Multiple Accounts: YES",
      "Email Alias: 10",
      "10GB Storage/acc",
      "300 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-business&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-business&billingcycle=annually`,
    linkText: "Get Business",
    featured: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: { BWP: "120", USD: "8.95" },
    priceYearly: { BWP: "1200", USD: "89.50" },
    description: "Perfect for large businesses and enterprises.",
    features: [
      "1 or more Accounts",
      "Multiple Accounts: YES",
      "Email Alias: 10",
      "50GB Storage/acc",
      "500 Emails/hour",
      "POP3/IMAP/SMTP",
      "Premium Email Deliverability",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-enterprise&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/business-email/titan-mail-enterprise&billingcycle=annually`,
    linkText: "Get Enterprise",
    featured: false,
  },
];
