export const HostingPlans = [
  {
    id: "startup",
    name: "Startup",
    priceMonthly: { BWP: "60", USD: "4.25" },
    priceYearly: { BWP: "600", USD: "42.50" },
    description: "Ideal for personal use and small businesses",
    features: [
      "2 Websites",
      "10 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificates",
      "5 Email Accounts",
      "WordPress Optimized",
      "Cpanel Included",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/startup&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/startup&billingcycle=annually`,
    linkText: "Get Startup",
    featured: false,
  },
  {
    id: "standard",
    name: "Standard",
    priceMonthly: { BWP: "120", USD: "8.50" },
    priceYearly: { BWP: "1200", USD: "85.00" },
    description: "Ideal for businesses and organisations.",
    features: [
      "5 Websites",
      "20 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificates",
      "10 Email Accounts",
      "WordPress Optimized",
      "Cpanel Included",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/standard&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/standard&billingcycle=annually`,
    linkText: "Get Standard",
    featured: true,
  },
  {
    id: "premium",
    name: "Premium",
    priceMonthly: { BWP: "195", USD: "14.00" },
    priceYearly: { BWP: "1950", USD: "140.00" },
    description: "Perfect for large businesses and enterprises.",
    features: [
      "10 Websites",
      "50 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificates",
      "20 Email Accounts",
      "WordPress Optimized",
      "Cpanel Included",
    ],
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/premium&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/premium&billingcycle=annually`,
    linkText: "Get Premium",
    featured: false,
  },
];
