export const HostingPlans = [
  {
    id: "startup",
    name: "Startup",
    priceMonthly: "P60",
    priceYearly: "P600",
    description: "ideal for personal use and small businesses",
    features: [
      "2 Websites",
      "10 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificate",
      "5 Email Accounts",
      "24/7/365 Support",
      "Cpanel Included",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/startup`,
    linkText: "Get Startup",
    featured: false,
  },
  {
    id: "standard",
    name: "Standard",
    priceMonthly: "P120",
    priceYearly: "P1200",
    description: "Ideal for businesses and organisations.",
    features: [
      "5 Websites",
      "20 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificate",
      "10 Email Accounts",
      "24/7/365 Support",
      "Cpanel Included",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/standard`,
    linkText: "Get Standard",
    featured: true,
  },
  {
    id: "premium",
    name: "Premium",
    priceMonthly: "P200",
    priceYearly: "P2000",
    description: "Perfect for large businesses and enterprises.",
    features: [
      "10 Websites",
      "50 GB SSD",
      "1TB Bandwidth",
      "Free SSL Certificate",
      "20 Email Accounts",
      "24/7/365 Support",
      "Cpanel Included",
    ],
    href: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/web-hosting/premium`,
    linkText: "Get Premium",
    featured: false,
  },
];
