import { VpsPlan } from "@/components/shared/pricing/vpspricing";

export const linuxVpsPricingData: VpsPlan[] = [
  {
    cpu: "LVPS-1",
    vCores: 1,
    ram: "1GB",
    storage: "15GB",
    bandwidth: "1TB",
    network: "1 IPv4",
    monthlyPrice: "P85",
    annualPrice: "P850",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-1&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-1&billingcycle=annually`,
  },
  {
    cpu: "LVPS-2",
    vCores: 1,
    ram: "2GB",
    storage: "30GB",
    bandwidth: "5TB",
    network: "1 IPv4",
    monthlyPrice: "P125",
    annualPrice: "P1250",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-2&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-2&billingcycle=annually`,
  },
  {
    cpu: "LVPS-4",
    vCores: 2,
    ram: "4GB",
    storage: "60GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: "P195",
    annualPrice: "P1950",
    popular: true,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-4&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-4&billingcycle=annually`,
  },
  {
    cpu: "LVPS-6",
    vCores: 3,
    ram: "6GB",
    storage: "90GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: "P260",
    annualPrice: "P2600",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-6&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-6&billingcycle=annually`,
  },
  {
    cpu: "LVPS-8",
    vCores: 4,
    ram: "8GB",
    storage: "120GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: "P330",
    annualPrice: "P3300",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-8&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-8&billingcycle=annually`,
  },
  {
    cpu: "LVPS-12",
    vCores: 6,
    ram: "12GB",
    storage: "180GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: "P470",
    annualPrice: "P4700",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-12&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/linux-vps/lvps-12&billingcycle=annually`,
  },
];
