import type { Metadata } from "next";
import "@/app/ui/global.css";
import "@/app/ui/main-nav.css";
import "@/app/ui/claudenav.css";
import { inter, notoSans } from "@/app/ui/fonts";
import ClaudeNav from "@/components/claudenav";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "bigZee - Web dev agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-background`}>
        {/* <ClaudeNav /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
