import { VpsPlan } from "@/components/shared/pricing/vpspricing";

export const windowsVpsPricingData: VpsPlan[] = [
  {
    cpu: "Win-4",
    vCores: 2,
    ram: "4GB",
    storage: "80GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: "P250",
    annualPrice: "P2500",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-4&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-4&billingcycle=annually`,
  },
  {
    cpu: "Win-6",
    vCores: 3,
    ram: "6GB",
    storage: "110GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: "P330",
    annualPrice: "P3300",
    popular: true,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-6&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-6&billingcycle=annually`,
  },
  {
    cpu: "Win-8",
    vCores: 4,
    ram: "8GB",
    storage: "150GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: "P410",
    annualPrice: "P4100",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-8&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-8&billingcycle=annually`,
  },
  {
    cpu: "Win-12",
    vCores: 6,
    ram: "12GB",
    storage: "200GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: "P580",
    annualPrice: "P5800",
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-12&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-12&billingcycle=annually`,
  },
];
