import { VpsPlan } from "@/components/shared/pricing/vpspricing";

export const windowsVpsPricingData: VpsPlan[] = [
  {
    cpu: "Win-4",
    vCores: 2,
    ram: "4GB",
    storage: "80GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: { BWP: "250", USD: "18.95" },
    annualPrice: { BWP: "2500", USD: "189.50" },
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-4&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-4&billingcycle=annually`,
  },
  {
    cpu: "Win-6",
    vCores: 3,
    ram: "6GB",
    storage: "110GB",
    bandwidth: "10TB",
    network: "1 IPv4",
    monthlyPrice: { BWP: "330", USD: "24.00" },
    annualPrice: { BWP: "3300", USD: "240.00" },
    popular: true,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-6&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-6&billingcycle=annually`,
  },
  {
    cpu: "Win-8",
    vCores: 4,
    ram: "8GB",
    storage: "150GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: { BWP: "410", USD: "30.50" },
    annualPrice: { BWP: "4100", USD: "305.00" },
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-8&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-8&billingcycle=annually`,
  },
  {
    cpu: "Win-12",
    vCores: 6,
    ram: "12GB",
    storage: "200GB",
    bandwidth: "20TB",
    network: "1 IPv4",
    monthlyPrice: { BWP: "580", USD: "42.00" },
    annualPrice: { BWP: "5800", USD: "420.00" },
    popular: false,
    monthlyUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-12&billingcycle=monthly`,
    annualUrl: `${process.env.NEXT_PUBLIC_WHMCS_URL}/index.php?rp=/store/windows-vps/win-12&billingcycle=annually`,
  },
];
