export const slides = [
  {
    url: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2620&q=80",
    title: "Modern design Principles",
    text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo.Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. ",
    imgUrl: "/img/lady-yellow.png",
    width: 500,
    height: 500,
    imgClass: "h-40 object-contain object-center pb-4",
  },
  {
    url: "/img/tech-man.jpg",
    title: "Security",
    text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo.",
    imgUrl: "/img/security.png",
    width: 2016,
    height: 456,
    imgClass: "h-[min(152px,40cqw)] object-cover object-center z-10",
  },
  {
    url: "/img/lady-laptop.jpg",
    className: "bg-neutral-200  border border-gray-400",
    title: "Powerfull Servers",
    text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo.",
  },
  {
    url: "/img/tech-man.jpg",
    title: "Performance",
    text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo.",
    imgUrl: "/img/performance.png",
    width: 948,
    height: 306,
    imgClass: "px-10 w-full max-lg:max-w-xs pb-12 z-10",
  },
];
